### ISSUE TITLE
[Bug]: Bottles crashes when trying to delete a bottle

### ISSUE THREAD

**Issue by HBRJZ** [bottlesdevs/Bottles#4679]
### Describe the bug

Bottles crashes when trying to delete a bottle.

### To Reproduce

1. Create a new bottle
2. Restart bottles
3. Open the bottle settings and pick "Delete bottle"
4. Restart Bottles
5. A window shows up saying bottles crashed, the bottle was not deleted.

### Package

Flatpak from Flathub

### Distribution

EndeavourOS (Arch Linux)

### Debugging Information

```shell
Official Package: true
Version: '66.1'
DE/WM: /usr/share/wayland-sessions/plasma.desktop
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        amd:
            vendor: amd
            envs:
                DRI_PRIME: '1'
            icd: /usr/share/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/radeon_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/radeon_icd.i686.json
    prime:
        integrated: null
        discrete: null
    Vulkan: true
Kernel:
    Type: Linux
    Version: 7.1.8-arch1-3
Disk:
    Total: 16600498176
    Free: 16600330240
RAM:
    MemTotal: 30.9GiB
    MemAvailable: 14.9GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
'NoneType' object has no attribute 'get'  File "/app/share/bottles/bottles/backend/utils/threading.py", line 73, in __target
    result = self.task_func(*args, **kwargs)

  File "/app/share/bottles/bottles/backend/managers/manager.py", line 2778, in delete_bottle
    if entry.get("bottle").get("name") == config.Name:
       ^^^^^^^^^^^^^^^^^^^^^^^
```

### Additional context

My bottles are stored outside of Bottles' ".var" folder. The folder is correctly set in the settings and Bottles has "RW" access to the folder.

Deleting bottles also worked fine in version 65.3.
