### ISSUE TITLE
[Bug]: DXVK NVAPI does not work.

### ISSUE THREAD

**Issue by Booo3** [bottlesdevs/Bottles#3720]
### Describe the bug

It seems that dlls in games is still not working like in the issue #1013. When i select the option in the settings it seems to error out.

### To Reproduce

Open Bottles 
Open Bottle
Go into settings
Enable "Deep Learning Super Sampling"
Reopen Bottles
Option is disabled again.

### Package

Flatpak from Flathub

### Distribution

Fedora Linux 41 (Workstation Edition)

### Debugging Information

```shell
Official Package: true
Version: '51.18'
DE/WM: gnome
Display:
    X.org: true
    X.org (port): :0
    Wayland: true
Graphics:
    vendors:
        nvidia: &amp;id002
            vendor: nvidia
            envs:
                __NV_PRIME_RENDER_OFFLOAD: '1'
                __GLX_VENDOR_LIBRARY_NAME: nvidia
                __VK_LAYER_NV_optimus: NVIDIA_only
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
            nvngx_path: /usr/lib/x86_64-linux-gnu/GL/nvidia-565-77/extra/nvidia/wine
        intel: &amp;id001
            vendor: intel
            envs:
                DRI_PRIME: '1'
            icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.x86_64.json:/usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/intel_icd.x86_64.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_hasvk_icd.i686.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/intel_icd.i686.json
    prime:
        integrated: *id001
        discrete: *id002
Kernel:
    Type: Linux
    Version: 6.12.9-200.fc41.x86_64
Disk:
    Total: 8293859328
    Free: 8293670912
RAM:
    MemTotal: 15.4GiB
    MemAvailable: 10.7GiB
Bottles_envs: null
```

### Troubleshooting Logs

```shell
Traceback (most recent call last):
  File "/app/share/bottles/bottles/frontend/views/bottle_preferences.py", line 623, in __toggle_nvapi
/home/boo3/.var/app/com.usebottles.bottles/data/bottles/nvapi/dxvk-nvapi-v0.8.0/x32/nvapi.dll -> /home/boo3/.var/app/com.usebottles.bottles/data/bottles/bottles/Uplay/drive_c/windows/syswow64/nvapi.dll
    self.__toggle_feature(widget=None, state=state, key="dxvk_nvapi")
TypeError: PreferencesView.__toggle_feature() got an unexpected keyword argument 'widget'
/home/boo3/.var/app/com.usebottles.bottles/data/bottles/nvapi/dxvk-nvapi-v0.8.0/x64/nvapi64.dll -> /home/boo3/.var/app/com.usebottles.bottles/data/bottles/bottles/Uplay/drive_c/windows/system32/nvapi64.dll
/usr/lib/x86_64-linux-gnu/GL/nvidia-565-77/extra/nvidia/wine/nvngx.dll -> /home/boo3/.var/app/com.usebottles.bottles/data/bottles/bottles/Uplay/drive_c/windows/system32/nvngx.dll
/usr/lib/x86_64-linux-gnu/GL/nvidia-565-77/extra/nvidia/wine/_nvngx.dll -> /home/boo3/.var/app/com.usebottles.bottles/data/bottles/bottles/Uplay/drive_c/windows/system32/_nvngx.dll
16:21:58 (INFO) Importing bundle to Uplay registry 
16:21:58 (INFO) Using Wine Registry CLI -- import_bundle 
16:21:59 (WARNING) Bottles runtime was requested but not found 
fsync: up and running.
16:22:00 (INFO) Import bundle result: ''
```

**Comment by seghir-netizen** [comment]
i have the same problem on Linux Mint , Bottles Flatpak.

**Comment by seghir-netizen** [comment]
i think this change "Remove support for the runtime sandbox" what caused the problem.

**Comment by TheEvilSkeleton** [comment]
> i think this change "Remove support for the runtime sandbox" what caused the problem.

No, that's a separate thing. It seems to have been caused by https://github.com/bottlesdevs/Bottles/commit/1f6e112daff927a9fadccff7487edc370195e664. I don't have an NVIDIA GPU, so that option never appeared, and thus I wasn't able to test.

**Comment by RedSnt** [comment]
I had to roll back to 51.13 (`flatpak update --commit=f7b9c259816528b2afa90c7852a218a4fb8ea4d121364214a546cfe2b0da1176 com.usebottles.bottles`) to fix this one bug (for now).   

As it's present in the flatpak version I can confirm that it happens in both Nobara 41 (wayland, fedora based) and MX Linux (X11, debian based).

**Comment by Bogster13** [comment]
I have the opposite problem
The toggle for DLSS keeps turning itself back on

Open Bottles
Open Bottle
Go into settings
Disable "Deep Learning Super Sampling"
Reopen Bottles
Option is Enabled again.

Reverting to the previous version has solved it temporarily.

**Package**

Flatpak from Flathub

**Distribution**

Arch Linux
